openapi: 3.0.1
info:
  title: MerchantPay
  description: API Definition of MerchantPay
  version: 1.0.0
servers:
- url: http://localhost:8290/merchant
paths:
  /pay:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
